### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by symful** [KaolinFlow/Kaolin.Flow#2]
- [ ] create http server
- [ ] create websocket client and server
- [ ] create promise/task to provide asynchronous
  - [ ] asyncify some plugins
- [x] create error handling etc.
- [ ] create a module repository thing
- [ ] create a separate repository to create a GUI plugin for mobile, desktop, and web
  - [ ] make a new console based on the plugin
